name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t dojo-jump-ci:1.0 .

      # Step 4: Run Docker container
      - name: Run Docker container
        run: |
          docker run -itd -p 8080:80 --name dojo-jump-c dojo-jump-ci:1.0

      # Optionally: Clean up Docker container and image after the workflow
      - name: Clean up Docker
        run: |
          docker stop dojo-jump-c
          docker rm dojo-jump-c
          docker rmi dojo-jump-ci:1.0
        if: always()

